name: CI

on:
  pull_request:
  push:
    branches: ["master", "develop"]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Read node version from .nvmrc
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"
          cache: "npm"
      - run: npm ci

      - name: Generate ESLint report
        run: npm run lint -- --output-file eslint_report.json --format json
        continue-on-error: true
      - name: Annotate report
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
        continue-on-error: true
      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report.json
          path: eslint_report.json
